# Check for broken links with lychee
name: Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: "--verbose -- ."
          fail: true
          jobSummary: true
